"""added otp table

Revision ID: 33441c78bc2b
Revises: 7fffa374562b
Create Date: 2024-08-18 12:32:50.354490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33441c78bc2b'
down_revision = '7fffa374562b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255),
               type_=sa.NVARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.NVARCHAR(length=255),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=255),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=True)

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('role_name',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=False)

    op.drop_table('otp')
    # ### end Alembic commands ###
