"""added auth tables

Revision ID: 7fffa374562b
Revises: 
Create Date: 2024-08-17 21:41:54.187394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7fffa374562b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('last_name', sa.NVARCHAR(length=100), nullable=True),
    sa.Column('email', sa.NVARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=False),
    sa.Column('passwords', sa.Text(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], name='users_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('role_name',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               type_=sa.NVARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('role_name',
               existing_type=sa.NVARCHAR(length=100),
               type_=mysql.VARCHAR(charset='utf8', collation='utf8_general_ci', length=100),
               existing_nullable=False)

    op.drop_table('users')
    # ### end Alembic commands ###
